spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://chunee.db.elephantsql.com:5432/qnluwbcj
    hikari:
      username: qnluwbcj
      password: DaLY1tWWYljkSy9Tm30vA_ax1dVDICCK

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
