spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    hikari:
      username: sa
      password: sa
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/registry/eureka

user:
  rabbitmq:
    exchange: user.exchange
    routingkey: user.auth.routingkey
