spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://postgres://qnluwbcj:DaLY1tWWYljkSy9Tm30vA_ax1dVDICCK@chunee.db.elephantsql.com/qnluwbcj

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/registry/eureka
